---
pagetitle: Journal Articles
page-layout: full
toc-location: left
---

## Stan Language and Algorithms

* Bob Carpenter, Andrew Gelman, Matthew D. Hoffman, Daniel Lee, Ben
  Goodrich, Michael Betancourt, Marcus Brubaker, Jiqiang Guo,
  Peter Li, and Allen Riddell.  2017.  Stan: A probabilistic
  programming language.  *Journal of Statistical Software* 76(1).
  [10.18637/jss.v076.i01](http://dx.doi.org/10.18637/jss.v076.i01)

* Aki Vehtari, Andrew Gelman, and Jonah Gabry. 2016.
  Practical Bayesian model evaluation using leave-one-out
  cross-validation and WAIC. *Statistics and Computing*.
  doi:10.1007/s11222-016-9696-4.

* Robert L. Grant, Daniel C. Furr, Bob Carpenter, and Andrew
  Gelman. 2016. Fitting Bayesian item response models in Stata and
  Stan. *arXiv* 1601.03443.

* Andrew Gelman, Daniel Lee, and Jiqiang Guo.  2015.  Stan:
  A probabilistic programming language for Bayesian inference
  and optimization.  *Journal of Education and Behavioral
  Statistics*. 40(5):530--543.

* Alp Kucukelbir, Rajesh Ranganath, Andrew Gelman and David
  M. Blei. 2015. Automatic Variational Inference in Stan, *NIPS*.

* Bob Carpenter, Matthew D. Hoffman, Marcus Brubaker, Daniel Lee,
  Peter Li, and Michael J. Betancourt.  2015.  The Stan Math Library:
  Reverse-Mode Automatic Differentiation in C++. *arXiv* 1509.07164.


## Hamiltonian Monte Carlo

* Michael Betancourt. 2017. A Conceptual Introduction to
  Hamiltonian Monte Carlo.  *arXiv*:1701.02434.

* Cole C. Monnahan, James T. Thorson, and Trevor A. Branch. 2016.
  Faster estimation of Bayesian models in ecology using
  Hamiltonian Monte Carlo. *Methods in Ecology and Evolution*.

* Michael J. Betancourt. 2016.  Identifying the Optimal Integration
  Time in Hamiltonian Monte Carlo. *arXiv*:1601.00225.

* Matthew D. Hoffman and Andrew Gelman.  2014.  The No-U-Turn Sampler:
  Adaptively Setting Path Lengths in Hamiltonian Monte Carlo.
  *Journal of Machine Learning Research*.  15(Apr):1593--1623.

* Michael J. Betancourt, Mark Girolami. 2013.  Hamiltonian Monte Carlo
  for Hierarchical Models. *arXiv* 1312.0906.

* Michael J. Betancourt. 2013.  A General Metric for Riemannian
  Manifold Hamiltonian Monte Carlo. *arXiv* 1212.4693.

* Michael J. Betancourt. 2013.  Generalizing the No-U-Turn Sampler to
  Riemannian Manifolds.  *arXiv* 1304.1920.

* Radford Neal. 2011. [http://www.mcmchandbook.net/HandbookChapter5.pdf](MCMC
  Using Hamiltonian Dynamics).  In *Handbook of Markov Chain Monte
  Carlo*, edited by Steve Brooks, Andrew Gelman, Galin L. Jones,
  and Xiao-Li Meng.  Chapman-Hall/CRC.

                       
## Variational Methods

* Pathfinder

* ADVI


## Bayesian Workflow

* Workflow paper

* Aki papers - PSIS-LOO-CV                       

                       
## Books using Stan

* Suzuki, J.  2023. [*WAIC and WBIC with R Stan: 100 Exercises for Building Logic*](https://link.springer.com/book/10.1007/978-981-99-3838-4).  Springer.

* Matsuura, K.. 2022. [*Bayesian Statistical Modeling with Stan, R, and
  Python.*](https://link.springer.com/book/10.1007/978-981-19-4755-1) Springer.

* Holmes, E. E., M. D. Scheuerell, and E. J. Ward.  2019.
  [*Applied Time Series Analysis for Fisheries and Environmental Sciences*](
  https://nwfsc-timeseries.github.io/atsa-labs/). NOAA Fisheries,
  Northwest Fisheries Science Center.

* Hilbe, J. M., R.S. de Souza, and E. E. O. Ishida.  2017. *Bayesian
  Models for Astrophysical Data Using R, JAGS, Python and Stan*.
  Cambridge University Press.

* Matsuura, K.. 2016. *Bayesian Statistical Modeling Using Stan
  and R*. Wonderful R Series, Volume 2. Kyoritsu Shuppan Co.,
  Ltd.  [in Japanese]

* McElreath, R.  2016.  *Statistical Rethinking:  A Bayesian
  Course with R and Stan*.  Chapman-Hall/CRC.

* Korner-Nievergelt, F., Roth, T., Von Felten, S., Guélat, J., Almasi,
  B. and Korner-Nievergelt, P.  2015. *Bayesian Data Analysis in
  Ecology Using Linear Models with R, BUGS, and Stan*.  Academic Press.

* Kruschke, J. 2014.  *Doing Bayesian Data Analysis: A Tutorial with R,
  JAGS, and Stan*. Academic Press.

* Gelman, A., Carlin, J.B., Stern, H.S., Dunson, D.B., Vehtari, A. and
  Rubin, D.B. 2013. *Bayesian Data Analysis*, Third
  Edition. Chapman-Hall/CRC.

