---
title: "Stan Interfaces and Tools"
page-layout: full
toc-location: left
---

<style>
  th:nth-child(2), td:nth-child(2) {
     background-color: var(--stan-bg);
  }
</style>

<table>
  <tr>
    <th style="width: 20%;"></th>
    <th style="width: 15%;" >Language</th>
    <th style="width: 65%;"></th>
  </tr>
  <tr style="background-color: var(--stan-highlight);">
    <td><b>Stan Interfaces</b></td>
    <td style="background-color: var(--stan-highlight);"></td>
    <td>Write, compile, and run new Stan models</td>
  </tr>
  <tr>
    <td></td>
    <td>Julia</td>
    <td><a href="http://stanjulia.github.io/Stan.jl/stable/INTRO/">Stan.jl</a></td>
  </tr>
  <tr>
    <td></td>
    <td>Python</td>
    <td>
      <a href="https://mc-stan.org/cmdstanpy">CmdStanPy</a>*,
      <a href="https://mc-stan.org/pystan">PyStan</a>
    </td>
  </tr>
  <tr>
    <td></td>
    <td>R</td>
    <td>
      <a href="https://mc-stan.org/cmdstanr">CmdStanR</a>*,
      <a href="https://mc-stan.org/rstan">RStan</a>
    </td>
  </tr>
  <tr>
    <td></td>
    <td></td>
    <td><b>*Note:</b> CmdStanPy and CmdStanR are recommended for new users;<br>PyStan and RStan continue to be supported.</td>
  </tr>
  <tr>
    <td></td>
    <td>shell</td>
    <td><a href="https://mc-stan.org/cmdstan">CmdStan</a></td>
  </tr>
  <tr style="background-color: var(--stan-highlight);">
    <td><b>High-level Interfaces</b></td>
    <td style="background-color: var(--stan-highlight);"></td>
    <td>Use existing Stan models</td>
  </tr>
  <tr>
    <td></td>
    <td>R</td>
    <td>
      <a href="https://paul-buerkner.github.io/brms/">BRMS</a><br>
      Specify and fit multivariate and multilevel models in Stan using extended R-formula syntax.
    </td>
  </tr>
  <tr>
    <td></td>
    <td>R</td>
    <td>
      <a href="https://mc-stan.org/rstanarm">RStanArm</a><br>
      Pre-compiled Stan versions of existing R model functions.
    </td>
  </tr>
  <tr style="background-color: var(--stan-highlight);">
    <td><b>Posterior Analysis Tools</b></td>
    <td style="background-color: var(--stan-highlight);"></td>
    <td>Validate, visualize, and compare fitted models</td>
  </tr>
  <tr>
    <td></td>
    <td>Julia</td>
    <td>[ArviZ.jl](https://julia.arviz.org/ArviZ/stable/)</td>
  </tr>
  <tr>
    <td></td>
    <td>Python</td>
    <td>[ArviZ](https://python.arviz.org/en/stable/)</td>
  </tr>
  <tr>
    <td></td>
    <td>R</td>
    <td>
      <a href="https://mc-stan.org/bayesplot/">Bayesplot</a> - plot model outputs,
      <a href="https://mc-stan.org/loo/">loo</a> - leave-one-out cross validation<br/>
      <a href="https://mc-stan.org/posterior">posterior</a> - get model estimates,
      <a href="https://mc-stan.org/projpred">projpred</a> - check model predictions
    </td>
  </tr>
  <tr>
    <td></td>
    <td>Web browser</td>
    <td><a href="https://github.com/flatironinstitute/mcmc-monitor">MCMC Monitor</a></td>
  </tr>
  <tr style="background-color: var(--stan-highlight);">
    <td><b>For Algorithm Developers</b></td>
    <td style="background-color: var(--stan-highlight);"></td>
    <td>Access Stan model methods from higher-level languages</td>
  </tr>
  <tr>
    <td></td>
    <td>Julia, Python, R, Rust</td>
    <td><a href="https://roualdes.github.io/bridgestan/latest/">BridgeStan</a><br/>
    Library with bindings to a model's log densities, gradients, Hessians, and constraining and unconstraining transforms. 
    </td>
  </tr>
  <tr style="background-color: var(--stan-highlight);">
    <td><b>For Package Developers</b></td>
    <td style="background-color: var(--stan-highlight);"></td>
    <td>Build tools that use Stan</td>
  </tr>
  <tr>
    <td></td>
    <td>C++</td>
    <td><a href="https://mc-stan.org/math/">stan-dev/math</a></td>
  </tr>
  <tr>
    <td></td>
    <td>R</td>
    <td><a href="https://mc-stan.org/rstantools/">rstantools</a></td>
  </tr>
</table>
